version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"  # Expose the HTTP port
      - "9300:9300"  # Expose the transport port (for internal cluster communications)
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
